Support for EXPIREAT
jazzband/django-redis pull request #472
Opened 2020-10-09 18:15 UTC by cashaev

Adding support for EXPIREAT key timestamp method in DefaultClient and ShardedClient.
Test.

2020-10-09 18:24 UTC, WisdomPill commented
Looks okay, 
I think that this method and some others need to give back the result of the operation (a boolean).

It is my first PR review, so I ask @jdufresne to confirm if everything looks okay.

2020-10-09 18:27 UTC, cashaev commented
> Looks okay,
> I think that this method and some others need to give back the result of the operation (a boolean).
> 
> It is my first PR review, so I ask @jdufresne to confirm if everything looks okay.

Maybe so. But adding the result should definitely be consistent across all the methods, and possibly done in a separate PR?
Otherwise, this PR's scope will expand too much.
@WisdomPill Thank you very much for a prompt reply!

2020-10-10 04:36 UTC, WisdomPill reviewed
Thanks for solving #471 as well

2020-10-27 07:54 UTC, WisdomPill approved these changes
Looks good to me

2020-11-13 10:23 UTC, WisdomPill commented
Hello @cashaev can you rebase on master so that we can merge this?

Thanks

2020-11-19 15:20 UTC, cashaev commented
Any action on this PR? I need this functionality again now )))

2020-11-19 15:22 UTC, cashaev commented
> Hello @cashaev can you rebase on master so that we can merge this?
> 
> Thanks

let me try

2020-11-19 15:38 UTC, cashaev commented
> Hello @cashaev can you rebase on master so that we can merge this?
> 
> Thanks

Sorry, not sure if I can do it correctly. Any assistance? Do I need to reopen it from my master branch?

2020-11-19 16:17 UTC, jdufresne commented
Please rebase. This should not contain changes to `.github/workflows/`, but they current show up in the diff.

2021-03-21 07:00 UTC, WisdomPill commented
@cashaev let me explain the steps to rebase on `django-redis/master`.

- locally add another remote pointing to `jazzband/django-redis` with the following command: `git remote add upstream git@github.com:jazzband/django-redis.git`
- fetch from remote master `git fetch upstream master`
- make sure to be on your master with the following command: `git checkout master`. Or just check with `git status`
- rebase your master (`origin/master`) on jazzband's master with the following command: `git rebase upstream/master`
- rebase your feature branch on your own master with the following two commands `git checkout expireat` and `git rebase origin/master`
- if there will be a need to merge and stuff you will get prompts, after that you can push with `git push --force origin expireat`, force is needed because you are changing the history of you branch.

Theoretically you could skip rebasing your master on upstream/master, but it is just good practice to keep everything in sync.

Hope this helps, let me know if you need more assistance

2021-05-02 02:18 UTC, terencehonles approved these changes
LGTM, but I'm not sure if we want to be implementing _every_ redis command in this class. @WisdomPill thoughts? You want to squash this if you're good with it so we can include it in the next release?

2021-05-02 05:49 UTC, WisdomPill commented
I think it is just a utility method recycling `.expire` method so it is okay to add it, I am worried that many commands are implemented only in `DefaultClient` so I think other clients could use some enhancements to be able to do the same things as `DefaultClient`.

2021-05-02 05:51 UTC, WisdomPill requested changes

2021-05-02 05:51 UTC, WisdomPill commented on tests/test_backend.py
> +        """
Can this be a multiline comment?

2021-05-02 05:51 UTC, WisdomPill commented on tests/test_backend.py
> +        """
```suggestion
        # Test settings expiration time 1 hour in past, which
        # effectively deletes the key.
        
```

2021-05-02 05:51 UTC, WisdomPill commented on django_redis/client/default.py
> +    def expire_at(self, key, when: Union[datetime, int], version=None, client=None):
```suggestion
    def expire_at(self, key: Any, when: Union[datetime, int], version: Optional[int]=None, client: Optional[Redis]=None):
```

2021-05-03 17:22 UTC, terencehonles commented
@WisdomPill I just applied your suggestions myself. If you're good with it as is, I'll let you handle squashing this.

2021-05-03 17:25 UTC, WisdomPill approved these changes

2021-05-03 17:26 UTC, WisdomPill commented
Thanks @terencehonles!

2021-05-03 17:26 UTC, WisdomPill commented
wait a mement

2021-05-03 17:27 UTC, WisdomPill requested changes
`when` can be a `datetime` but using a date time will get an exception, `datetime` needs to be converted to unix timestamp

2021-05-03 18:33 UTC, terencehonles commented
> `when` can be a `datetime` but using a date time will get an exception, `datetime` needs to be converted to unix timestamp

Where? The tests cover sending both a `datetime` and an `int`, so that's covered there. The underlying client (if `redis-py`) handles converting to an `int` https://github.com/andymccurdy/redis-py/blob/1a41cfd95a53a95b078084d8627be6b6fba3bb71/redis/client.py#L1659-L1660

2021-05-03 18:39 UTC, WisdomPill commented
Okay, sorry did not notice that redis py supports it, my bad

2021-05-06 08:08 UTC, merged