Add Python 3.9 to CI
jazzband/django-redis pull request #477
Opened 2020-10-14 15:30 UTC by peymanslh

Changes:
- Add Python 3.9 to TravisCI config file

Closes: #474

2020-10-14 17:36 UTC, WisdomPill commented
There is no python 3.9 yet on travis, python3.9 has been released just 10 days ago and travis still needs to support it.

They only support python3.9-dev as of now.

Please switch to python3.9-dev for this moment and leave it on the allowed to fail builds

2020-10-14 17:39 UTC, WisdomPill requested changes
use py39-dev because py39 is not yet available

2020-10-15 00:00 UTC, jdufresne commented
What is the reason only "djangomaster" is being tested by Travis? Why not all Django targets?

2020-10-15 16:25 UTC, peymanslh commented
> What is the reason only "djangomaster" is being tested by Travis? Why not all Django targets?

I saw Python 3.8 was only tested with `django master`.
We have `django22`, `django30`, `django31`, and `djangomaster` in `tox.ini`.
Should I add all of these for Python `3.9-dev`?

2020-10-15 18:42 UTC, WisdomPill commented
> I checked Python 3.8 and it was only tested with django master.

Where have you seen that?

2020-10-15 20:59 UTC, hugovk commented
How about adding the Trove classifier to `setup.cfg` too?

```
    Programming Language :: Python :: 3.9
```

2020-10-15 22:53 UTC, jdufresne commented on .travis.yml
> +    - env: TOXENV=py39-dev-django31-redismaster
Thanks for keeping at it!

```suggestion
```

IMO, only `djangomaster` should allow failures, as it is unstable and changing. Python 3.9 is stable and no new PRs should break it.

2020-10-15 23:27 UTC, peymanslh commented
@jdufresne Thanks for your review.
I've fixed the conflict with the last commit.

2020-10-16 01:04 UTC, jdufresne approved these changes
LGTM. Thanks!

@WisdomPill Let me know if you'd like to a take a last look.

2020-10-16 08:11 UTC, WisdomPill approved these changes
Nice job, thanks to everybody who contributed

2020-10-16 08:12 UTC, merged