Specified ACL login usage in the README
jazzband/django-redis pull request #482
Opened 2020-11-13 09:47 UTC by GrazingScientist

It took me some digging in the redis-py source code (their README does not even hint this feature). Hence, I thought it may be useful to have it explicitely in the documentation for others

2020-11-13 10:21 UTC, WisdomPill requested changes
Thanks for pointing it out, now that you are at it can you add an example with `"OPTIONS"`?

2020-11-13 10:33 UTC, WisdomPill approved these changes

2020-11-13 10:35 UTC, GrazingScientist commented
Thanks for kicking me! :)

I left the previous code block with the `OPTIONS` example in the documentation, because it shows that the `OPTIONS` password can also be used without the ACL credentials.

2020-11-21 16:40 UTC, WisdomPill approved these changes

2020-11-21 16:41 UTC, merged