Log traceback if exceptions are ignored
jazzband/django-redis pull request #613
Opened 2022-06-24 12:32 UTC by tmarice

Fixes #611

2022-06-29 17:53 UTC, WisdomPill requested changes

2022-07-03 08:20 UTC, tmarice commented
@WisdomPill codecov is complaining that the patch isn't covered with tests, so I'll add some that verify that the full traceback was logged.

I'm not sure the mypy failure is related to this PR, though.

2022-07-20 16:39 UTC, tmarice commented
@WisdomPill Do you mind taking another look at the PR?

2022-11-07 11:21 UTC, merged

2022-11-07 11:22 UTC, WisdomPill commented
sorry for being late, and very much thank you for the contribution